lv.init()
var scr = lv.lv_scr_act()
var btn = lv.lv_btn_create(scr)
var label1 = lv.lv_label_create(scr)
lv.lv_label_set_text(label1, 'Hello, world!')
var label2 = lv.lv_label_create(btn)
lv.lv_label_set_text(label2, "OK")
lv.lv_obj_set_pos(btn, 30,30)
lv.run()